version: '3'
services:
  postgres:
    image: postgres:14.7
    container_name: 'strapi-postgres-db'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi
    volumes:
      - ./db/data:/var/lib/postgresql/data
  app:
    image: node:18.16.0
    container_name: 'strapi-app'
    ports:
      - 1337:1337
    volumes:
      - ./strapi:/opt/strapi
    working_dir: /opt/strapi
    tty: true
    depends_on: 
      - postgres
